apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-fezinhadasorte-cluster-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@fezinhadasorte.com
    privateKeySecretRef:
      name: letsencrypt-fezinhadasorte
    solvers:
    - http01:
      ingress:
        class: nginx
