apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-campanha-microservice
  namespace: producao-api-campanha
  annotations:
    nginx.org/mergeable-ingress-type: "minion"
spec:
  ingressClassName: nginx
  rules:
  - host: www.fezinhadasorte.com
    http:
      paths:
      - path: /api/eventos-campanha
        pathType: Prefix
        backend:
          service:
            name: campanha-microservice-clusterip-service
            port:
              number: 80