argo-cd:
  replicaCount: 3
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
  config:
    server:
      baseHref: /argocd/
      rootPath: /argocd/
      staticAssets:
        enabled: true
        path: /shared/app
    insecure: true
    logFormat: text
    logLevel: info
  ingress:
    enabled: true
    ingressClassName: "kong"
    hosts:
      - fezinhadasorte.com
    paths:
      - /argocd
    pathType: Prefix
