server:
  ingress:
    enabled: true
    ingressClassName: "kong"
    hosts:
      - fezinhadasorte.com
    paths:
      - /argocd
    # -- Ingress path type. One of `Exact`, `Prefix` or `ImplementationSpecific`
    pathType: Prefix
    # -- Additional ingress paths
    extraPaths: []
      # - path: /*
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: ssl-redirect
      #       port:
      #         name: use-annotation
