argo-cd:
  replicaCount: 3
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
  config:
    server:
      basehref: /argocd/
  ingress:
    enabled: true
    ingressClassName: "kong"
    hosts:
      - fezinhadasorte.com
    paths:
      - /argocd
    pathType: Prefix
