params:
  server.insecure: true
  server.basehref: /argocd
  server.rootpath: '/argocd'
server:
  extraArgs:
   - --insecure
  replicas: 3
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
  ingress:
    enabled: true
    ingressClassName: "kong"
    hosts:
      - fezinhadasorte.com
    paths:
      - /argocd
    pathType: Prefix
