crds:
  install: false
global:
  securityContext:
    runAsUser: 999
    fsGroup: 999
configs:
  params:
    server.insecure: true
    server.disable.auth: true
    server.basehref: /argocd/
    server.rootpath: '/argocd/'
    server.staticassets: /shared/app
  cm:
    timeout.reconciliation: 10s
server:
  autoscaling:
    enabled: true
    minReplicas: 2
repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2
