crds:
  install: false
global:
  logging:
    format: text
    level: info
configs:
  params:
    server.insecure: true
    server.basehref: /argocd/
    server.rootpath: '/argocd/'
    server.staticassets: /shared/app
redis:
  containerPorts:
    redis: 6379
dex:
  containerPorts:
    http: 5556
redis-ha:
  enabled: true
controller:
  replicas: 1
server:
  autoscaling:
    enabled: true
    minReplicas: 2
  ingress:
    enabled: true
    ingressClassName: "kong"
    hosts:
      - fezinhadasorte.com
    paths:
      - /argocd
    pathType: Prefix
repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2
  containerPorts:
    server: 8081
applicationSet:
  replicaCount: 2
