crds:
  install: false
global:
  securityContext:
    runAsUser: 999
    fsGroup: 999
  logging:
    format: text
    level: info
configs:
  params:
    "server.insecure": true
    "server.disable.auth": true
    "server.basehref": /argocd/
    "server.rootpath": '/argocd/'
    "server.staticassets": /shared/app
redis:
  containerPorts:
    redis: 6379
dex:
  containerPorts:
    http: 5556
redis-ha:
  enabled: false
controller:
  replicas: 1
server:
  autoscaling:
    enabled: true
    minReplicas: 1
  ingress:
    enabled: true
    ingressClassName: "kong"
    hosts:
      - fezinhadasorte.com
    paths:
      - /argocd
    pathType: Prefix
repoServer:
  autoscaling:
    enabled: true
    minReplicas: 1
  containerPorts:
    server: 8081
applicationSet:
  replicaCount: 1
