apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd-new
spec:
  project: default
  source:
    repoURL: https://github.com/nginxinc/helm-charts
    targetRevision: "3.15.2"
    chart: ingress-nginx
    helm:
      values: |
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
