apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: nginx
spec:
  project: default
  source:
    repoURL: https://github.com/luizgusmao/kind-kong.git
    targetRevision: HEAD
    path: apps/nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
