apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: processamento-resultado-concurso-microservice
  namespace: producao-argo-cd-new
spec:
  project: default
  source:
    repoURL: https://github.com/luizgusmao/IAC-fezinhadasorte.git
    targetRevision: HEAD
    path: apps/processamento-resultado-concurso
  destination:
    server: https://kubernetes.default.svc
    namespace: producao-api-proc-resultado-concurso
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
