apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: ingress-nginx
spec:
  project: default
  source:
    repoURL: https://helm.nginx.com/stable
    targetRevision: ""
    chart: nginx-ingress
    helm:
      values: |
        controller:
          replicaCount: 2
          metrics:
            enabled: true
          config:
            use-forwarded-headers: "true"
          service:
            loadBalancerIP: "35.237.165.35"
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
