apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://codecentric.github.io/helm-charts
    targetRevision: "18.4.0"
    chart: keycloak
    helm:
      values:
        service:
          type: NodePort
        ingress:
          enabled: true
          annotations:
            konghq.com/protocol: https
            konghq.com/https-redirect-status-code: "301"
          ingressClassName: kong
          hosts: 
            - fezinhadasorte.com
          paths:
            - /auth(/|$)(.*)
          pathType: Prefix
        env:
          KEYCLOAK_LOGLEVEL: DEBUG
          KEYCLOAK_USER: admin
          KEYCLOAK_PASSWORD: as897gsdfs766dfsgjhsdf
          PROXY_ADDRESS_FORWARDING: 'true'
          KEYCLOAK_ADMIN: admin
          KEYCLOAK_ADMIN_PASSWORD: as897gsdfs766dfsgjhsdf
          KC_PROXY: edge
          KC_HOSTNAME: fezinhadasorte.com
          KC_HOSTNAME_STRICT_HTTPS: 'true'
          KC_LOG_LEVEL: INFO
          KC_DB: postgres
          KC_DB_URL: jdbc:postgresql://10.15.112.3:5432/keycloak
          KC_DB_USERNAME: keycloak
          KC_DB_PASSWORD: test123
          KC_TRANSACTION_XA_ENABLED: 'true'
          KC_HEALTH_ENABLED: 'true'
          KC_METRICS_ENABLED: 'true'
  destination:
    server: https://kubernetes.default.svc
    namespace: auth
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
