apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-fezinhadasorte
  namespace: producao-argo-cd-new
spec:
  project: default
  source:
    repoURL: https://github.com/bitnami/charts.git
    path: bitnami/wordpress
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: producao-wordpress
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
