apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.konghq.com
    targetRevision: "2.19.0"
    chart: kong
    helm:
      parameters:
      - name: "ingressController.installCRDs"
        value: 'false'
        forceString: true # ensures that value is treated as a string
      - name: "ingressController.env.controller_log_level"
        value: "debug"
      - name: "proxy.loadBalancerIP"
        value: "35.237.165.35"
      values: |
        deployment:
          sidecarContainers:
            - name: tcpdump
              securityContext:
                runAsUser: 0
              image: corfr/tcpdump
              command:
                - /bin/sleep
                - infinity
        certificates:
          enabled: true
          issuer: "GlobalSign Root CA"
        admin:
          ingress:
            tls: certificate-fezinhadasorte-locaweb-256g4
        proxy:
          tls: 
            enabled: true
            servicePort: 443
            containerPort: 8443
          http:
            enabled: false
        podAnnotations:
          prometheus.io/scrape: "true" # Ask Prometheus to scrape the
          prometheus.io/port: "8100"   # Kong pods for metrics
        # plugins:
        #   configMaps:                # change this to 'secrets' if you created a secret
        #   - name: kong-plugin-myheader
        #     pluginName: myheader
  destination:
    server: https://kubernetes.default.svc
    namespace: kong
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
