apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd-new
spec:
  project: default
  source:
    repoURL: https://helm.nginx.com/stable
    targetRevision: "0.17.0"
    chart: nginx-ingress
    helm:
      values: |
        controller:
          replicaCount: 2
          metrics:
            enabled: true
          ingressClass: nginx
          config:
            use-forwarded-headers: "true"
          service:
            loadBalancerIP: "35.237.165.35"
            ipFamilies: "IPv4"
            ipFamilyPolicy: "SingleStack"
          autoscaling:
            enabled: true
        prometheus:
          create: true
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
