apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd-new
spec:
  project: default
  source:
    repoURL: https://codecentric.github.io/helm-charts
    targetRevision: "18.4.0"
    chart: keycloak
    helm:
      values: |
        service:
          type: ClusterIP
        postgresql:
          enabled: false
        ingress:
          enabled: true
          servicePort: https
          annotations: 
            kubernetes.io/ingress.static-ip-name: fezinhadasorte-ip-external
            nginx.ingress.kubernates.io/rewrite-target: /$1    
            nginx.ingress.kubernetes.io/ssl-redirect: 'false'
            nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
            nginx.ingress.kubernetes.io/enable-cors: "true"
            nginx.ingress.kubernetes.io/secure-backends: "true"
            cert-manager.io/cluster-issuer: "letsencrypt-fezinhadasorte-cluster-issuer"
          tls:
          - hosts:
            - "www.fezinhadasorte.com"
            - "fezinhadasorte.com"
            secretName: letsencrypt-fezinhadasorte
          ingressClassName: nginx
          rules:
            - host: fezinhadasorte.com
              paths:
                - path: /auth
                  pathType: Prefix
            - host: www.fezinhadasorte.com
              paths:
                - path: /auth
                  pathType: Prefix
        extraEnv: |
          - name: KEYCLOAK_LOGLEVEL
            value: 'DEBUG'
          - name: KEYCLOAK_USER
            value: 'admin'
          - name: KEYCLOAK_PASSWORD
            value: 'as897gsdfs766dfsgjhsdf'
          - name: PROXY_ADDRESS_FORWARDING
            value: 'true'
          - name: KEYCLOAK_ADMIN
            value: 'admin'
          - name: KEYCLOAK_ADMIN_PASSWORD
            value: 'as897gsdfs766dfsgjhsdf'
          - name: KC_PROXY
            value: 'edge'
          - name: KC_HOSTNAME
            value: fezinhadasorte.com
          - name: KC_HOSTNAME_STRICT_HTTPS
            value: 'true'
          - name: KC_LOG_LEVEL
            value: 'INFO'
          - name: KC_DB
            value: 'postgres'
          - name: KC_DB_URL
            value: 'jdbc:postgresql://10.15.112.3:5432/postgres'
          - name: KC_DB_USERNAME
            value: 'keycloak'
          - name: KC_DB_PASSWORD
            value: 'test123'
          - name: KC_TRANSACTION_XA_ENABLED
            value: 'true'
          - name: KC_HEALTH_ENABLED
            value: 'true'
          - name: KC_METRICS_ENABLED
            value: 'true'
  destination:
    server: https://kubernetes.default.svc
    namespace: auth
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-fezinhadasorte-cluster-issuer
  namespace: auth
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@fezinhadasorte.com
    privateKeySecretRef:
      name: letsencrypt-fezinhadasorte
    solvers:
    - http01:
        ingress:
          class: nginx
