apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: producao
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: "20.2.0"
    chart: prometheus
    helm:
      values: |
        server:
          global:
            scrape_interval: 10s
  destination:
    server: https://kubernetes.default.svc
    namespace: producao
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
