apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cliente-microservice
  namespace: producao-argocd
spec:
  project: default
  source:
    repoURL: https://github.com/luizgusmao/IAC-fezinhadasorte.git
    targetRevision: HEAD
    path: apps/cliente-microservice
  destination:
    server: https://kubernetes.default.svc
    namespace: producao-microservices
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
