apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-v21
  namespace: producao-argo-cd-new
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: producao-keycloak
  project: default
  source:
    repoURL: "https://github.com/luizgusmao/IAC-Fezinhadasorte.git"
    path: apps/keycloak-v21
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      # - Replace=true
