apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: front-end-fezinhadasorte
  namespace: producao-argo-cd-new
spec:
  project: default
  source:
    repoURL: https://github.com/luizgusmao/IAC-fezinhadasorte.git
    targetRevision: HEAD
    path: apps/fezinha-frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: producao-front-end
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
