apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://codecentric.github.io/helm-charts
    targetRevision: "18.4.0"
    chart: keycloak
    helm:
      values: |
        #args:
        #  - -Dkeycloak.profile.feature.docker=enabled
        #  tls:
        #  - hosts:
        #    - sso.ssotest.staging.talkingquickly.co.uk
        #    secretName: keycloak-tld-secret
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-production
          ingressClassName: kong
          hosts: 
            - fezinhadasorte.com
          path: /grafana
          pathType: Prefix
        extraEnv: |
        - name: KEYCLOAK_LOGLEVEL
          value: DEBUG
        - name: KEYCLOAK_USER
          value: admin
        - name: KEYCLOAK_PASSWORD
          value: as897gsdfs766dfsgjhsdf
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: KEYCLOAK_ADMIN
          value: 'admin'
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: 'as897gsdfs766dfsgjhsdf'
        - name: KC_PROXY
          value: 'edge'
        - name: KC_HOSTNAME
          value: fezinhadasorte.com
        - name: KC_HOSTNAME_STRICT_HTTPS
          value: 'true'
        - name: KC_LOG_LEVEL
          value: 'INFO'
        - name: KC_DB
          value: 'postgres'
        - name: KC_DB_URL
          value: 'jdbc:postgresql://10.15.112.3:5432/keycloak'
        - name: KC_DB_USERNAME
          value: 'keycloak'
        - name: KC_DB_PASSWORD
          value: 'test123'
        - name: KC_TRANSACTION_XA_ENABLED
          value: 'true'
        - name: KC_HEALTH_ENABLED
          value: 'true'
        - name: KC_METRICS_ENABLED
          value: 'true'
  destination:
    server: https://kubernetes.default.svc
    namespace: auth
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
