apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-loki
  namespace: producao-loki
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: "2.8.1"
    chart: grafana/loki
    helm:
      values: |
        minio:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: producao-loki
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
