apiVersion: v1
kind: Service
metadata:
  name: processamento-resultado-concurso-microservice-service
  namespace: producao-api-proc-resultado-concurso
spec:
  selector:
    app: processamento-resultado-concurso-microservice
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8080
    - name: https-api
      port: 8443
      protocol: TCP
      targetPort: 8080
    - name: http-api
      port: 80
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
  