apiVersion: v1
kind: Service
metadata:
  name: front-end-fezinhadasorte-clusterip-service
  namespace: ingress-nginx
spec:
  selector:
    app: front-end-fezinhadasorte
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
